City.create(name: 'Barra Bonita', state: 'Sao Paulo')
City.create(name: 'Igaracu do Tiete', state: 'Sao Paulo')
City.create(name: 'Mineiros do Tiete', state: 'Sao Paulo')
City.create(name: 'Macatuba', state: 'Sao Paulo')
City.create(name: 'Jau', state: 'Sao Paulo')
City.create(name: 'Lencois Paulista', state: 'Sao Paulo')
City.create(name: 'Dois Corregos', state: 'Sao Paulo')
City.create(name: 'Sao Manuel', state: 'Sao Paulo')
City.create(name: 'Torrinha', state: 'Sao Paulo')
City.create(name: 'Brotas', state: 'Sao Paulo')
City.create(name: 'Agudos', state: 'Sao Paulo')
City.create(name: 'Pederneiras', state: 'Sao Paulo')
City.create(name: 'Piracicaba', state: 'Sao Paulo')
City.create(name: 'Santa Maria da Serra', state: 'Sao Paulo')